In [265]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [266]:
teams = pd.read_csv("teams.csv")

In [267]:
teams

team  year  athletes  events   age  height  weight  prev_medals  medals
0     AFG  1964         8       8  22.0   161.0    64.2          0.0       0
1     AFG  1968         5       5  23.2   170.2    70.0          0.0       0
2     AFG  1972         8       8  29.0   168.3    63.8          0.0       0
3     AFG  1980        11      11  23.6   168.4    63.2          0.0       0
4     AFG  2004         5       5  18.6   170.8    64.8          0.0       0
...   ...   ...       ...     ...   ...     ...     ...          ...     ...
2009  ZIM  2000        26      19  25.0   179.0    71.1          0.0       0
2010  ZIM  2004        14      11  25.1   177.8    70.5          0.0       3
2011  ZIM  2008        16      15  26.1   171.9    63.7          3.0       4
2012  ZIM  2012         9       8  27.3   174.4    65.2          4.0       0
2013  ZIM  2016        31      13  27.5   167.8    62.2          0.0       0

[2014 rows x 9 columns]

In [268]:
train, test = train_test_split(teams, test_size=0.2, random_state=1)

In [269]:
predictors = ["athletes", "events"]
target = "medals"

In [270]:
X = train[predictors].copy()
y = train[[target]].copy()

In [271]:
X

athletes  events
1322         6       6
1872       119      80
953          4       4
1117         2       2
1993        43      25
...        ...     ...
1791        40      25
1096        36      23
1932       719     245
235         13      11
1061        50      38

[1611 rows x 2 columns]

In [272]:
y

medals
1322       0
1872       5
953        0
1117       0
1993       0
...      ...
1791       1
1096       1
1932     264
235        0
1061       3

[1611 rows x 1 columns]

In [273]:
x_mean = X.mean()
x_std = X.std()

In [274]:
x_mean

athletes    74.409063
events      35.990068
dtype: float64

In [275]:
X = (X - x_mean) / x_std

In [276]:
X.describe()

athletes        events
count  1.611000e+03  1.611000e+03
mean  -2.370681e-17 -9.923781e-18
std    1.000000e+00  1.000000e+00
min   -5.768883e-01 -7.143930e-01
25%   -5.297371e-01 -6.123079e-01
50%   -4.197174e-01 -4.489717e-01
75%   -2.679027e-02  1.839560e-01
max    6.008571e+00  4.634867e+00

In [277]:
X["intercept"] = 1

In [278]:
X = X[["intercept"] + predictors]

In [279]:
X.describe()

intercept      athletes        events
count     1611.0  1.611000e+03  1.611000e+03
mean         1.0 -2.370681e-17 -9.923781e-18
std          0.0  1.000000e+00  1.000000e+00
min          1.0 -5.768883e-01 -7.143930e-01
25%          1.0 -5.297371e-01 -6.123079e-01
50%          1.0 -4.197174e-01 -4.489717e-01
75%          1.0 -2.679027e-02  1.839560e-01
max          1.0  6.008571e+00  4.634867e+00

In [280]:
X.T

1322      1872      953       1117      1993      385   \
intercept  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
athletes  -0.537596  0.350420 -0.553313 -0.569030 -0.246829 -0.482586   
events    -0.612308  0.898552 -0.653142 -0.693976 -0.224384 -0.571474   

               1287      1831      0         1159  ...      960       847   \
intercept  1.000000  1.000000  1.000000  1.000000  ...  1.000000  1.000000   
athletes  -0.537596  0.138239 -0.521879 -0.152527  ... -0.199678 -0.160386   
events    -0.612308  0.102288 -0.571474 -0.163133  ... -0.285636 -0.101882   

               1669      715       905       1791      1096      1932  \
intercept  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
athletes  -0.529737 -0.529737 -0.341132 -0.270405 -0.301839  5.065546   
events    -0.612308 -0.591891 -0.367304 -0.224384 -0.265219  4.267361   

               235       1061  
intercept  1.000000  1.000000  
athletes  -0.482586 -0.191820  
events    -0.510223  0.041037  

[3 rows x 1611 columns]

In [281]:
alpha = 2
I = np.identity(X.shape[1])

In [282]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [283]:
I [0] [0] = 0

In [284]:
I

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [285]:
penalty = alpha * I

In [286]:
penalty

array([[0., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [287]:
B = np.linalg.inv(X.T @ X + penalty) @ X.T @ y

In [288]:
B

medals
0  10.691496
1  61.857734
2 -34.632920

In [289]:
B.index = ["intercept", "athletes", "events"]

In [290]:
B

medals
intercept  10.691496
athletes   61.857734
events    -34.632920

In [291]:
test_X = test[predictors]
test_X = (test_X - x_mean) / x_std
test_X["intercept"] = 1
test_X = test_X[["intercept"] + predictors]

In [292]:
test_X

intercept  athletes    events
309           1 -0.553313 -0.653142
285           1  0.594035  1.000637
919           1 -0.144668  0.102288
120           1  0.146098  0.531045
585           1 -0.301839 -0.122299
...         ...       ...       ...
541           1 -0.380425 -0.408138
1863          1 -0.191820  0.143122
622           1 -0.058224  0.388126
1070          1 -0.569030 -0.693976
1196          1 -0.553313 -0.653142

[403 rows x 3 columns]

In [293]:
predictions = test_X @ B

In [294]:
predictions

medals
309   -0.914959
285   12.782156
919   -1.799893
120    1.337116
585   -3.744014
...         ...
541    1.294285
1863  -6.130765
622   -6.352080
1070  -0.472980
1196  -0.914959

[403 rows x 1 columns]